spring:
  application:
    name: front-service

  mvc:
    hiddenmethod:
      filter:
        enabled: true
  data:
    redis:
      host: 220.67.216.14
      port: 6379
      password: '*N2vya7H@muDTwdNMR!'
      default_db: 201
      cart_db: 202

server:
  port: 8100

onebook:
  gatewayUrl: http://localhost:8200

# redis 관련 설정
# 주석처리된 것: nhn cloud의 secret키 관련 설정임.
# 문의사항: 김주혁에게
#  url: https://api-keymanager.nhncloudservice.com
#  appKey: qTQNj7LyHhdAazH3
#  keyPath: 1nebook.p12
#  password: 1nebook
#  keyId: a53e608fbf3744a594162277fb824907

